<?php

namespace ArsThanea\PageMediaSetBundle\Entity;

use ArsThanea\PageMediaSetBundle\Service\HasMediaSetInterface;
use Doctrine\ORM\EntityRepository;

/**
 * PageMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMediaRepository extends EntityRepository
{
    public function getPageMediaSet(HasMediaSetInterface $page)
    {
        return $this->findBy([
            'pageType' => $page->getType(),
            'pageId' => $page->getId()
        ]);
    }
}
